--- #YAML:1.0
name: AudioFile-Info-MP3-Info
version: 1.02
author:
  - Dave Cross, E<lt>dave@dave.org.ukE<gt>
abstract: Perl extension to get info from MP3 files.
license: perl
requires:
  AudioFile::Info: 0
  MP3::Info: 0
  perl: 5.6.0
build_requires:
  Module::Build: 0
dynamic_config: 1
provides:
  AudioFile::Info::Build:
    file: lib/AudioFile/Info/Build.pm
  AudioFile::Info::MP3::Info:
    file: lib/AudioFile/Info/MP3/Info.pm
    version: 1.02
generated_by: Module::Build version 0.2607
